services:
  localstack:
    image: localstack/localstack:0.14.4
    container_name: aws_infra_localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: 's3,ec2,ecs,rds,iam,secretsmanager,cloudwatch'
      DEBUG: '0'
      LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT: '1'
      DEFAULT_REGION: 'us-east-1'
    volumes:
      - ./tmp/localstack:/tmp/localstack
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/health']
      interval: 10s
      timeout: 5s
      retries: 20

  terraform:
    image: hashicorp/terraform:1.6.6
    working_dir: /workspace/infra/environments/dev
    volumes:
      - ./:/workspace
    environment:
      AWS_REGION: us-east-1
      TERRAFORM_INIT_OPTS: '-input=false -lock=true'
      TERRAFORM_PLAN_OPTS: '-no-color'
      TERRAFORM_APPLY_OPTS: '-auto-approve'
    depends_on:
      localstack:
        condition: service_healthy
    entrypoint: ['terraform']

  library-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    ports:
      - '8080:8080'
    depends_on:
      - localstack
    environment:
      SPRING_PROFILES_ACTIVE: local
